//! Docs site generator (`anza docs`) — markdown + config.toml → dist-first tree.
//!
//! See plans/DOCS-GENERATOR.md.

mod config;
mod transform;

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

use config::{DocsConfig, Files, SidebarItem, SidebarSection};
use transform::{md_to_html_body, route_from_md, tag_from_route};

pub use config::load_config;

#[derive(Debug, Clone)]
pub struct DocsOptions {
  pub config: PathBuf,
  pub out: Option<PathBuf>,
  /// When true, only emit pages listed in sidebar + entry home (MVP default).
  pub sidebar_only: bool,
}

#[derive(Debug)]
struct Page {
  md_path: PathBuf,
  /// Absolute site route, e.g. `/docs/intro/start`
  route: String,
  title: String,
  body_html: String,
}

pub fn run(opts: &DocsOptions) -> Result<(), String> {
  let config_path = resolve_config(&opts.config)?;
  let cfg = load_config(&config_path)?;
  let docs_root = config_path
    .parent()
    .ok_or_else(|| "config.toml has no parent directory".to_string())?
    .to_path_buf();

  let out = opts
    .out
    .clone()
    .unwrap_or_else(|| resolve_out(&docs_root, &cfg.site.out));

  if out.exists() {
    fs::remove_dir_all(&out).map_err(|e| format!("clear {}: {e}", out.display()))?;
  }
  fs::create_dir_all(&out).map_err(|e| format!("mkdir {}: {e}", out.display()))?;

  let pages = collect_pages(&docs_root, &cfg, opts.sidebar_only)?;
  if pages.is_empty() {
    return Err("no markdown pages to emit".into());
  }

  copy_assets(&docs_root, &out, &cfg)?;
  write_view_code_loader(&out)?;
  write_app_js(&out)?;
  write_chrome_css(&out)?;

  let mut barrel_imports: Vec<String> = Vec::new();

  for page in &pages {
    emit_page(&out, &cfg, page)?;
    let rel_js = route_to_dist_js(&page.route, &cfg.entry.route);
    barrel_imports.push(format!("import '{}';", rel_js));
  }

  // Root docs barrel (soft-nav registration stubs).
  let barrel = out.join("docs").join("index.js");
  fs::create_dir_all(barrel.parent().unwrap()).ok();
  let mut barrel_src = String::from("// Generated by anza docs — page module barrel\n");
  for line in &barrel_imports {
    barrel_src.push_str(line);
    barrel_src.push('\n');
  }
  fs::write(&barrel, barrel_src).map_err(|e| format!("write barrel: {e}"))?;

  emit_redirects(&out, &cfg)?;
  emit_root_index(&out, &cfg)?;
  emit_seo_files(&out, &cfg, &pages)?;

  if cfg.entry.landing {
    emit_landing(&out, &docs_root, &cfg)?;
  }

  anza_logs::success!(
    "Docs site generated → {} ({} pages)",
    out.display(),
    pages.len()
  );
  anza_logs::info!(
    "Smoke: cd {} && python3 -m http.server 8765  (open /docs/ or /docs/intro/start/)",
    out.display()
  );
  anza_logs::info!(
    "Note: python http.server needs a trailing slash for directory indexes; soft-nav app.js maps /docs/... → .../index.html"
  );

  Ok(())
}

fn resolve_config(path: &Path) -> Result<PathBuf, String> {
  let p = if path.is_absolute() {
    path.to_path_buf()
  } else {
    std::env::current_dir()
      .map_err(|e| e.to_string())?
      .join(path)
  };
  if p.is_file() {
    return Ok(p);
  }
  // Allow passing docs/ directory.
  let nested = p.join("config.toml");
  if nested.is_file() {
    return Ok(nested);
  }
  Err(format!(
    "docs config not found at {} (expected docs/config.toml)",
    path.display()
  ))
}

fn resolve_out(docs_root: &Path, configured: &str) -> PathBuf {
  let p = PathBuf::from(configured);
  if p.is_absolute() {
    return p;
  }
  // Prefer repo root (parent of docs/) for relative outs like tmp/docs-site.
  docs_root
    .parent()
    .unwrap_or(docs_root)
    .join(configured)
}

fn collect_pages(
  docs_root: &Path,
  cfg: &DocsConfig,
  sidebar_only: bool,
) -> Result<Vec<Page>, String> {
  let mut paths: BTreeSet<PathBuf> = BTreeSet::new();

  // Entry home
  paths.insert(docs_root.join(&cfg.entry.home));

  for section in &cfg.sidebar {
    for item in &section.items {
      if item.hide {
        continue;
      }
      paths.insert(docs_root.join(&item.path));
    }
  }

  if !sidebar_only {
    collect_file_globs(docs_root, &cfg.files, &mut paths)?;
  }

  let mut pages = Vec::new();
  for md_path in paths {
    if !md_path.is_file() {
      anza_logs::warn!("skip missing markdown: {}", md_path.display());
      continue;
    }
    let raw = fs::read_to_string(&md_path).map_err(|e| format!("read {}: {e}", md_path.display()))?;
    let (fm_title, body_md) = strip_frontmatter(&raw);
    let route = if md_path == docs_root.join(&cfg.entry.home) {
      cfg.entry.route.clone()
    } else {
      route_from_md(&md_path, docs_root, &cfg.site.base)?
    };
    let body_html = md_to_html_body(&body_md, &md_path, docs_root, &cfg.site.base)?;
    let title = fm_title
      .or_else(|| first_h1_text(&body_html))
      .unwrap_or_else(|| route.clone());
    pages.push(Page {
      md_path,
      route,
      title,
      body_html,
    });
  }

  pages.sort_by(|a, b| a.route.cmp(&b.route));
  Ok(pages)
}


fn collect_file_globs(
  docs_root: &Path,
  files: &Files,
  paths: &mut BTreeSet<PathBuf>,
) -> Result<(), String> {
  let roots: Vec<PathBuf> = if files.roots.is_empty() {
    vec![docs_root.to_path_buf()]
  } else {
    files.roots.iter().map(|r| docs_root.join(r)).collect()
  };
  for root in roots {
    if !root.is_dir() {
      anza_logs::warn!("skip missing files.roots dir: {}", root.display());
      continue;
    }
    for entry in WalkDir::new(&root).into_iter().filter_map(|e| e.ok()) {
      let path = entry.path();
      if !path.is_file() { continue; }
      if path.extension().and_then(|e| e.to_str()) != Some("md") { continue; }
      let rel = path.strip_prefix(docs_root).unwrap_or(path).to_string_lossy();
      if !files.include.is_empty() && !files.include.iter().any(|g| path_matches_glob(&rel, g)) { continue; }
      if files.exclude.iter().any(|g| path_matches_glob(&rel, g)) { continue; }
      paths.insert(path.to_path_buf());
    }
  }
  Ok(())
}

fn path_matches_glob(path: &str, pattern: &str) -> bool {
  let pattern = pattern.replace('\\', "/");
  let path = path.replace('\\', "/");
  if let Some(inner) = pattern.strip_prefix("**/") {
    return path.ends_with(inner) || path.contains(&format!("/{inner}"));
  }
  if pattern.contains('*') {
    let parts: Vec<&str> = pattern.split('*').collect();
    if parts.len() == 2 { return path.starts_with(parts[0]) && path.ends_with(parts[1]); }
  }
  path == pattern || path.ends_with(&format!("/{pattern}"))
}

fn strip_frontmatter(raw: &str) -> (Option<String>, String) {
  let trimmed = raw.trim_start();
  if !trimmed.starts_with("---") {
    return (None, raw.to_string());
  }
  let rest = &trimmed[3..];
  let Some(end) = rest.find("\n---") else {
    return (None, raw.to_string());
  };
  let yaml = &rest[..end];
  let body = rest[end + 4..].trim_start_matches('\n').to_string();
  let mut title = None;
  for line in yaml.lines() {
    let line = line.trim();
    if let Some(v) = line.strip_prefix("title:") {
      title = Some(v.trim().trim_matches('"').trim_matches('\'').to_string());
    }
  }
  (title, body)
}

fn first_h1_text(html: &str) -> Option<String> {
  let html = crate::build::html::opaque_view_code(html);
  let start = html.find("<h1>")? + 4;
  let end = html.get(start..)?.find("</h1>")? + start;
  let inner = html.get(start..end)?;
  let text = strip_tags(inner).trim().to_string();
  if text.is_empty() {
    None
  } else {
    Some(text)
  }
}

fn strip_tags(s: &str) -> String {
  let mut out = String::new();
  let mut in_tag = false;
  for c in s.chars() {
    match c {
      '<' => in_tag = true,
      '>' => in_tag = false,
      _ if !in_tag => out.push(c),
      _ => {}
    }
  }
  out
}

fn copy_assets(docs_root: &Path, out: &Path, cfg: &DocsConfig) -> Result<(), String> {
  let assets = &cfg.assets;
  let resolve = |p: &str| -> PathBuf {
    let path = PathBuf::from(p);
    if path.is_absolute() {
      path
    } else {
      docs_root.join(path)
    }
  };

  // Prefer a single pack root with conventional subfolders when set.
  if !assets.pack.is_empty() {
    let pack = resolve(&assets.pack);
    copy_pack_subdir(&pack, "styles", &out.join("styles"))?;
    copy_pack_subdir(&pack, "tokens", &out.join("tokens"))?;
    // views/code or view-code
    if pack.join("views").join("code").is_dir() {
      copy_dir_all(&pack.join("views").join("code"), &out.join("views").join("code"))?;
    } else if pack.join("view-code").is_dir() {
      copy_dir_all(&pack.join("view-code"), &out.join("views").join("code"))?;
    }
    if pack.join("images").is_dir() {
      copy_dir_all(&pack.join("images"), &out.join("images"))?;
    }
    if pack.join("docks").is_dir() {
      copy_dir_all(&pack.join("docks"), &out.join("docks"))?;
    }
    return Ok(());
  }

  // Explicit folder roots — copy whole directories (never enumerate CSS files).
  copy_dir_all(&resolve(&assets.styles), &out.join("styles"))?;
  copy_dir_all(&resolve(&assets.tokens), &out.join("tokens"))?;
  copy_dir_all(&resolve(&assets.view_code), &out.join("views").join("code"))?;
  copy_dir_all(&resolve(&assets.docks), &out.join("docks"))?;

  if !assets.images.is_empty() {
    let images = resolve(&assets.images);
    if images.is_dir() {
      copy_dir_all(&images, &out.join("images"))?;
    } else {
      anza_logs::warn!("assets.images not a directory: {}", images.display());
    }
  }

  Ok(())
}

fn copy_pack_subdir(pack: &Path, name: &str, dest: &Path) -> Result<(), String> {
  let src = pack.join(name);
  if src.is_dir() {
    copy_dir_all(&src, dest)
  } else {
    Err(format!("pack missing {}/ under {}", name, pack.display()))
  }
}

fn copy_dir_all(src: &Path, dest: &Path) -> Result<(), String> {
  if !src.is_dir() {
    return Err(format!("asset dir missing: {}", src.display()));
  }
  fs::create_dir_all(dest).map_err(|e| e.to_string())?;
  for entry in walkdir::WalkDir::new(src).into_iter().filter_map(|e| e.ok()) {
    let path = entry.path();
    let rel = path.strip_prefix(src).unwrap();
    let target = dest.join(rel);
    if path.is_dir() {
      fs::create_dir_all(&target).map_err(|e| e.to_string())?;
    } else if path.is_file() {
      if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
      }
      fs::copy(path, &target).map_err(|e| e.to_string())?;
    }
  }
  Ok(())
}

fn write_view_code_loader(out: &Path) -> Result<(), String> {
  // Standalone CE for smoke without full Anza UI graph.
  let js = r#"/**
 * Generated view-code loader (MVP) — Prism highlight + copy.
 * Full Anza view('view-code') remains the production target.
 */
import './views/code/prism.js';

class ViewCode extends HTMLElement {
  connectedCallback() {
    const lang = this.getAttribute('language') || 'text';
    const text = (this.textContent || '').replace(/^\n/, '').replace(/\n$/, '');
    this.textContent = '';

    const wrap = document.createElement('div');
    wrap.className = 'code-block';

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'copy-btn';
    btn.setAttribute('aria-label', 'Copy');
    btn.textContent = 'Copy';
    btn.addEventListener('click', async () => {
      try {
        await navigator.clipboard.writeText(text);
        btn.textContent = 'Copied';
        setTimeout(() => { btn.textContent = 'Copy'; }, 1500);
      } catch (_) {}
    });

    const pre = document.createElement('pre');
    const code = document.createElement('code');
    code.className = `language-${lang}`;
    code.textContent = text;
    pre.appendChild(code);
    wrap.appendChild(btn);
    wrap.appendChild(pre);
    this.appendChild(wrap);

    if (window.Prism) {
      window.Prism.highlightElement(code);
    }
  }
}

if (!customElements.get('view-code')) {
  customElements.define('view-code', ViewCode);
}
"#;
  fs::write(out.join("view-code.js"), js).map_err(|e| e.to_string())
}

fn write_app_js(out: &Path) -> Result<(), String> {
  let js = r#"/**
 * MVP soft-nav: intercept same-origin /docs links, swap .doc-body.
 * Full Anza page()/dock soft-nav is the Phase 2+ target (page modules emitted as stubs).
 */
import './view-code.js';
import './docs/index.js';

function indexUrl(pathname) {
  let p = pathname.replace(/\/+$/, '') || '/';
  if (p === '/docs') return '/docs/index.html';
  return `${p}/index.html`;
}

function highlightSidebar(pathname) {
  const path = pathname.replace(/\/+$/, '') || '/';
  const links = document.querySelectorAll('.sidebar-nav a');
  let best = null;
  let bestLen = -1;
  for (const link of links) {
    const href = (link.getAttribute('href') || '').replace(/\/+$/, '') || '/';
    if (path === href || path.startsWith(href + '/')) {
      if (href.length > bestLen) {
        best = link;
        bestLen = href.length;
      }
    }
  }
  for (const link of links) {
    link.classList.toggle('active', link === best);
  }
}

async function softNav(pathname, push) {
  const url = indexUrl(pathname);
  const res = await fetch(url);
  if (!res.ok) {
    location.href = url;
    return;
  }
  const html = await res.text();
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const next = doc.querySelector('.doc-body');
  const cur = document.querySelector('.doc-body');
  if (!next || !cur) {
    location.href = url;
    return;
  }
  cur.replaceChildren(...next.childNodes);
  document.title = doc.title;
  if (push) history.pushState({}, '', pathname);
  highlightSidebar(pathname);
  // Re-upgrade any view-code nodes (connectedCallback already ran on parse? cloned nodes need define)
  for (const el of cur.querySelectorAll('view-code')) {
    // already upgraded if CE defined before parse of fetched HTML... fetch parse creates HTMLUnknownElement
    // Force upgrade by replacing with fresh element
    const neu = document.createElement('view-code');
    const lang = el.getAttribute('language');
    if (lang) neu.setAttribute('language', lang);
    neu.textContent = el.textContent;
    el.replaceWith(neu);
  }
}

document.addEventListener('click', (e) => {
  const a = e.target.closest('a');
  if (!a) return;
  const href = a.getAttribute('href');
  if (!href || href.startsWith('#') || /^[a-z]+:/i.test(href)) return;
  if (href.startsWith('/docs') || href === '/docs') {
    e.preventDefault();
    softNav(href, true);
  }
});

window.addEventListener('popstate', () => {
  softNav(location.pathname, false);
});

highlightSidebar(location.pathname);
"#;
  fs::write(out.join("app.js"), js).map_err(|e| e.to_string())
}

fn write_chrome_css(out: &Path) -> Result<(), String> {
  // Minimal layout glue on top of docks chrome CSS + shared.css
  let css = r#"
html, body { margin: 0; padding: 0; min-height: 100%; }
body.docs-mvp {
  font-family: var(--font-sans, system-ui, sans-serif);
  background: var(--bg-color, #fff);
  color: var(--text-color, #111);
}
.docs-mvp .docs-header { position: sticky; top: 0; z-index: 10; }
.docs-mvp .doc-main {
  max-width: 52rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem 3rem;
}
.docs-mvp view-code { display: block; }
.docs-mvp .code-block {
  position: relative;
  border-radius: 12px;
  overflow: auto;
  background: var(--bg-code, #1e1e1e);
  color: #eee;
  padding: 0.75rem 1rem;
  margin: 1rem 0;
}
.docs-mvp .code-block pre { margin: 0; }
.docs-mvp .copy-btn {
  position: absolute;
  top: 8px;
  right: 10px;
  font-size: 0.75rem;
  cursor: pointer;
}
"#;
  fs::write(out.join("styles").join("mvp.css"), css).map_err(|e| e.to_string())
}

fn emit_page(out: &Path, cfg: &DocsConfig, page: &Page) -> Result<(), String> {
  let dir = route_to_dir(out, &page.route, &cfg.entry.route)?;
  fs::create_dir_all(&dir).map_err(|e| e.to_string())?;

  let html = render_shell(cfg, page);
  fs::write(dir.join("index.html"), html).map_err(|e| e.to_string())?;

  // Soft-nav page module stub (future Anza page() registration).
  let tag = tag_from_route(&page.route, &cfg.site.base);
  let via = cfg
    .entry
    .via
    .iter()
    .map(|s| format!("'{s}'"))
    .collect::<Vec<_>>()
    .join(", ");
  let js = format!(
    r#"// Generated stub — full Anza page() wiring lands when docs emit uses library runtime.
// source: {source}
// route: {route}
export const route = '{route}';
export const tag = '{tag}';
export const via = [{via}];
export const template = {{ html: './index.html' }};
export const style = ['/styles/shared.css'];
console.debug('[anza docs]', route, tag);
"#,
    source = page.md_path.display(),
    route = page.route,
    tag = tag,
    via = via,
  );
  // Home HTML lives at docs/index.html; module stub at docs/home.js to avoid barrel self-import.
  let js_path = if page.route == cfg.entry.route {
    out.join("docs").join("home.js")
  } else {
    dir.join("index.js")
  };
  fs::write(js_path, js).map_err(|e| e.to_string())?;
  Ok(())
}

fn route_to_dir(out: &Path, route: &str, home_route: &str) -> Result<PathBuf, String> {
  if route == home_route {
    return Ok(out.join("docs"));
  }
  let trimmed = route.trim_start_matches('/');
  Ok(out.join(trimmed))
}

fn route_to_dist_js(route: &str, home_route: &str) -> String {
  // Paths relative to dist/docs/index.js barrel.
  if route == home_route {
    return "./home.js".into();
  }
  if let Some(rest) = route.strip_prefix("/docs/") {
    return format!("./{rest}/index.js");
  }
  format!("./{}/index.js", route.trim_start_matches('/'))
}

fn render_shell(cfg: &DocsConfig, page: &Page) -> String {
  let sidebar = render_sidebar(&cfg.sidebar, &page.route, &cfg.site.base);
  let title = format!("{} — {}", page.title, cfg.seo.site_name);
  let dock = esc(&cfg.entry.root_dock);
  let body_class = if cfg.entry.shell.is_empty() {
    "docs-mvp".to_string()
  } else {
    format!("docs-mvp {}", esc(&cfg.entry.shell))
  };
  let mut head_extras = String::new();
  let origin = cfg.seo.origin.trim_end_matches('/');
  if !origin.is_empty() {
    let canonical = format!("{origin}{}", page.route);
    head_extras.push_str(&format!(
      "  <link rel=\"canonical\" href=\"{}\" />\n",
      esc(&canonical)
    ));
  }
  if cfg.seo.json_ld {
    let url = if origin.is_empty() {
      page.route.clone()
    } else {
      format!("{origin}{}", page.route)
    };
    let ld = serde_json::json!({
      "@context": "https://schema.org",
      "@type": "WebPage",
      "name": page.title,
      "url": url,
    });
    head_extras.push_str(&format!(
      "  <script type=\"application/ld+json\">{}</script>\n",
      ld
    ));
  }
  format!(
    r##"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="alternate icon" href="/favicon.ico" type="image/x-icon" />
{head_extras}  <link rel="stylesheet" href="/tokens/index.css" />
  <link rel="stylesheet" href="/styles/index.css" />
  <link rel="stylesheet" href="/styles/shared.css" />
  <link rel="stylesheet" href="/docks/{dock}/index.css" />
  <link rel="stylesheet" href="/styles/mvp.css" />
  <link rel="stylesheet" href="/views/code/prism.css" />
  <link rel="stylesheet" href="/views/code/index.css" />
  <script type="module" src="/app.js"></script>
</head>
<body class="{body_class}">
  <header class="docs-header">
    <div class="header-inner">
      <a href="/" class="logo" aria-label="Anza home">
        <div class="logo-mark">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <defs>
              <linearGradient id="header-logo-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stop-color="#1ecf4e" />
                <stop offset="100%" stop-color="#80DBFF" />
              </linearGradient>
            </defs>
            <circle cx="12" cy="12" r="10" fill="url(#header-logo-gradient)" fill-opacity="0.12" stroke="url(#header-logo-gradient)" stroke-width="1.5"></circle>
            <path d="M9.38886 15.1629C9.89331 15.5 10.5955 15.5 12 15.5C13.4045 15.5 14.1067 15.5 14.6111 15.1629C14.8295 15.017 15.017 14.8295 15.1629 14.6111C15.5 14.1067 15.5 13.4045 15.5 12C15.5 10.5955 15.5 9.89331 15.1629 9.38886C15.017 9.17048 14.8295 8.98298 14.6111 8.83706C14.1067 8.5 13.4045 8.5 12 8.5C10.5955 8.5 9.89331 8.5 9.38886 8.83706C9.17048 8.98298 8.98298 9.17048 8.83706 9.38886C8.5 9.89331 8.5 10.5955 8.5 12C8.5 13.4045 8.5 14.1067 8.83706 14.6111C8.98298 14.8295 9.17048 15.017 9.38886 15.1629Z"
              fill="url(#header-logo-gradient)" fill-opacity="0.12" stroke="url(#header-logo-gradient)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
        </div>
        <span class="version">{site}</span>
      </a>
      <nav class="header-nav" aria-label="Primary">
        <a href="/docs" class="nav-link active">Docs</a>
      </nav>
    </div>
  </header>
  <div class="docs-container">
    <aside class="docs-sidebar-left">
      <nav class="sidebar-nav">
{sidebar}
      </nav>
    </aside>
    <main class="doc-main">
      <article class="doc-body page-content">
{body}
      </article>
    </main>
  </div>
</body>
</html>
"##,
    title = esc(&title),
    head_extras = head_extras,
    dock = dock,
    body_class = body_class,
    site = esc(&cfg.seo.site_name),
    sidebar = sidebar,
    body = page.body_html,
  )
}

fn render_sidebar(sections: &[SidebarSection], active: &str, _base: &str) -> String {
  let mut out = String::new();
  for (i, section) in sections.iter().enumerate() {
    if i > 0 {
      out.push_str("        <div class=\"sidebar-divider\"></div>\n");
    }
    let section_id = esc(&section.id);
    out.push_str(&format!(
      "        <details class=\"sidebar-group\" id=\"sidebar-{section_id}\" open>\n"
    ));
    out.push_str("          <summary class=\"sidebar-group-header\">\n");
    out.push_str(&format!("            <h3>{}</h3>\n", esc(&section.title)));
    out.push_str("          </summary>\n");
    out.push_str("          <div class=\"sidebar-group-links\">\n");
    let mut items: Vec<&SidebarItem> = section.items.iter().filter(|i| !i.hide).collect();
    items.sort_by(|a, b| match (a.order, b.order) {
      (Some(ao), Some(bo)) => ao.cmp(&bo),
      (Some(_), None) => std::cmp::Ordering::Less,
      (None, Some(_)) => std::cmp::Ordering::Greater,
      (None, None) => a.path.cmp(&b.path),
    });
    for item in items {
      let href = item_href(item, _base);
      let label = item
        .label
        .clone()
        .unwrap_or_else(|| fallback_label(&item.path));
      let class = if href == active || active.starts_with(&(href.clone() + "/")) {
        " class=\"active\""
      } else {
        ""
      };
      out.push_str(&format!(
        "            <a href=\"{href}\"{class}>{label}</a>\n",
        href = esc(&href),
        class = class,
        label = esc(&label),
      ));
    }
    out.push_str("          </div>\n");
    out.push_str("        </details>\n");
  }
  out
}

fn item_href(item: &SidebarItem, base: &str) -> String {
  let p = item.path.trim_end_matches(".md").replace('\\', "/");
  if p == "index" {
    return base.trim_end_matches('/').to_string();
  }
  format!("{}/{}", base.trim_end_matches('/'), p)
}

fn fallback_label(path: &str) -> String {
  Path::new(path)
    .file_stem()
    .and_then(|s| s.to_str())
    .unwrap_or(path)
    .to_string()
}

fn emit_redirects(out: &Path, cfg: &DocsConfig) -> Result<(), String> {
  for redir in &cfg.redirect {
    let trimmed = redir.from.trim_start_matches('/');
    let dir = out.join(trimmed);
    fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let html = format!(
      r#"<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8" />
<meta http-equiv="refresh" content="0;url={to}" />
<script>location.replace({to_js});</script>
<title>Redirect</title>
</head><body><p>Redirecting to <a href="{to}">{to}</a>…</p></body></html>
"#,
      to = esc(&redir.to),
      to_js = serde_json::to_string(&redir.to).unwrap_or_else(|_| "\"/\"".into()),
    );
    fs::write(dir.join("index.html"), html).map_err(|e| e.to_string())?;
  }
  Ok(())
}

fn emit_root_index(out: &Path, cfg: &DocsConfig) -> Result<(), String> {
  let to = &cfg.entry.route;
  let html = format!(
    r#"<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8" />
<meta http-equiv="refresh" content="0;url={to}" />
<script>location.replace({to_js});</script>
<title>{site}</title>
</head><body><p><a href="{to}">Open docs</a></p>
<script type="module" src="/app.js"></script>
</body></html>
"#,
    to = esc(to),
    to_js = serde_json::to_string(to).unwrap(),
    site = esc(&cfg.site.title),
  );
  fs::write(out.join("index.html"), html).map_err(|e| e.to_string())
}

fn emit_landing(out: &Path, docs_root: &Path, cfg: &DocsConfig) -> Result<(), String> {
  let dir = out.join("home");
  fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
  if !cfg.assets.landing.is_empty() {
    let landing_src = resolve_asset_path(docs_root, &cfg.assets.landing);
    let index = landing_src.join("index.html");
    if index.is_file() {
      fs::copy(&index, dir.join("index.html")).map_err(|e| e.to_string())?;
      return Ok(());
    }
    anza_logs::warn!("assets.landing has no index.html at {}", index.display());
  }
  // Stub landing at /home/ — root index redirects to /docs for smoke.
  let html = format!(
    r#"<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>{site}</title>
<link rel="stylesheet" href="/tokens/index.css" />
<link rel="stylesheet" href="/styles/index.css" />
<link rel="stylesheet" href="/styles/mvp.css" />
</head>
<body class="docs-mvp" style="padding:3rem 1.5rem;max-width:40rem;margin:0 auto;">
  <h1>{site}</h1>
  <p>Docs generator MVP landing (stub). Full <code>pages/entry</code> marketing template comes later.</p>
  <p><a href="/docs/">Open documentation</a></p>
</body></html>
"#,
    site = esc(&cfg.seo.site_name),
  );
  fs::write(dir.join("index.html"), html).map_err(|e| e.to_string())
}
fn resolve_asset_path(docs_root: &Path, configured: &str) -> PathBuf {
  let path = PathBuf::from(configured);
  if path.is_absolute() {
    path
  } else {
    docs_root.join(path)
  }
}

fn emit_seo_files(out: &Path, cfg: &DocsConfig, pages: &[Page]) -> Result<(), String> {
  let origin = cfg.seo.origin.trim_end_matches('/');
  if cfg.seo.robots {
    let mut robots = String::from("User-agent: *\nAllow: /\n");
    if !origin.is_empty() && cfg.seo.sitemap {
      robots.push_str(&format!("Sitemap: {origin}/sitemap.xml\n"));
    }
    fs::write(out.join("robots.txt"), robots).map_err(|e| e.to_string())?;
  }
  if cfg.seo.sitemap && !origin.is_empty() {
    let mut xml = String::from(
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n",
    );
    for page in pages {
      xml.push_str(&format!("  <url><loc>{}{}</loc></url>\n", origin, esc(&page.route)));
    }
    xml.push_str("</urlset>\n");
    fs::write(out.join("sitemap.xml"), xml).map_err(|e| e.to_string())?;
  }
  Ok(())
}

fn esc(s: &str) -> String {
  s.replace('&', "&amp;")
    .replace('<', "&lt;")
    .replace('>', "&gt;")
    .replace('"', "&quot;")
}
