// tools/src/generate/mod.rs
//
// Thin filesystem generators: `anza generate page|dock|view|part <name>`.
// Respects anza.json slot remaps; updates index barrels. Not a schematic platform.

use std::fs;
use std::path::{Path, PathBuf};

use crate::structure::project_from_src;

/// What to generate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
  Page,
  Dock,
  View,
  Part,
}

impl Kind {
  pub fn parse(s: &str) -> Result<Self, String> {
    match s {
      "page" => Ok(Kind::Page),
      "dock" => Ok(Kind::Dock),
      "view" => Ok(Kind::View),
      "part" => Ok(Kind::Part),
      other => Err(format!(
        "unknown kind '{}' — expected page, dock, view, or part",
        other
      )),
    }
  }

  pub fn as_str(self) -> &'static str {
    match self {
      Kind::Page => "page",
      Kind::Dock => "dock",
      Kind::View => "view",
      Kind::Part => "part",
    }
  }
}

/// Generator options (CLI flags).
#[derive(Debug, Clone, Default)]
pub struct Options {
  /// Folder / registry name (kebab-case).
  pub name: String,
  /// Page tree relative to src (must be in anza.json pages[] or default `pages`).
  pub tree: Option<String>,
  /// Page route path (default `/{name}`).
  pub route: Option<String>,
  /// Page via chain (default `[rootDock]`).
  pub via: Option<Vec<String>>,
  /// Dock parent registry key (default `rootDock`).
  pub parent: Option<String>,
}

/// Result of a successful generate.
#[derive(Debug)]
pub struct Generated {
  pub dir: PathBuf,
  pub barrel: PathBuf,
  pub kind: Kind,
  pub name: String,
}

/// Generate a page/dock/view/part into the resolved structure slots.
pub fn run(
  src_arg: &Path,
  kind: Kind,
  opts: &Options,
) -> Result<Generated, String> {
  let name = normalize_name(&opts.name)?;
  let (project, hint) = project_from_src(src_arg);
  let resolved = resolve_paths(&project, &hint);

  if !resolved.src.is_dir() {
    return Err(format!(
      "source directory missing: {} — run from an anza app (see docs/intro/structure.md)",
      resolved.src.display()
    ));
  }

  match kind {
    Kind::Page => gen_page(&resolved.src, &resolved.pages, &resolved.root_dock, &name, opts),
    Kind::Dock => gen_dock(&resolved.src, &resolved.docks, &resolved.root_dock, &name, opts),
    Kind::View => gen_ce(&resolved.src, &resolved.views, "view", &name),
    Kind::Part => gen_ce(&resolved.src, &resolved.parts, "part", &name),
  }
}

fn normalize_name(raw: &str) -> Result<String, String> {
  let name = raw.trim().trim_matches('/').to_lowercase();
  if name.is_empty() {
    return Err("name must not be empty".into());
  }
  if !name
    .chars()
    .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
  {
    return Err(format!(
      "invalid name '{}' — use letters, numbers, hyphen, underscore",
      raw
    ));
  }
  if name.starts_with('-') || name.ends_with('-') {
    return Err(format!("invalid name '{}' — do not start/end with '-'", raw));
  }
  Ok(name.replace('_', "-"))
}

fn gen_page(
  src: &Path,
  pages: &[String],
  root_dock: &str,
  name: &str,
  opts: &Options,
) -> Result<Generated, String> {
  let tree = opts
    .tree
    .clone()
    .unwrap_or_else(|| pages.first().cloned().unwrap_or_else(|| "pages".into()));
  if !pages.iter().any(|p| p == &tree) {
    return Err(format!(
      "page tree '{}' is not in anza.json pages[] {:?} — declare it or omit --tree",
      tree, pages
    ));
  }

  let route = opts
    .route
    .clone()
    .unwrap_or_else(|| format!("/{}", name));
  let via = opts
    .via
    .clone()
    .unwrap_or_else(|| vec![root_dock.to_string()]);
  let via_js = via
    .iter()
    .map(|v| format!("'{}'", v))
    .collect::<Vec<_>>()
    .join(", ");

  let tag = format!("page-{}", name);
  let dir = src.join(&tree).join(name);
  if dir.exists() {
    return Err(format!("already exists: {}", dir.display()));
  }

  let js = format!(
    r#"/**
 * src/{tree}/{name}/index.js
 */
import {{ page }} from '@adukiorg/anza/ui';

page('{route}', {{
  tag: '{tag}',
  via: [{via}],
  template: {{ html: './index.html', css: './index.css' }}
}}, import.meta.url);
"#,
    tree = tree,
    name = name,
    route = route,
    tag = tag,
    via = via_js,
  );

  let html = format!(
    r#"<article class="{name}">
  <h1>{title}</h1>
  <p>Generated by <code>anza generate page</code>.</p>
</article>
"#,
    name = name,
    title = title_case(name),
  );

  let css = format!(
    r#".{name} {{
  padding: var(--space-8, 2rem);
}}
"#,
    name = name
  );

  write_file(&dir.join("index.js"), &js);
  write_file(&dir.join("index.html"), &html);
  write_file(&dir.join("index.css"), &css);

  let barrel = ensure_barrel(src, &tree, &format!("./{}/index.js", name))?;
  Ok(Generated {
    dir,
    barrel,
    kind: Kind::Page,
    name: name.to_string(),
  })
}

fn gen_dock(
  src: &Path,
  docks_slot: &str,
  root_dock: &str,
  name: &str,
  opts: &Options,
) -> Result<Generated, String> {
  let parent = opts
    .parent
    .clone()
    .unwrap_or_else(|| root_dock.to_string());
  let dir = src.join(docks_slot).join(name);
  if dir.exists() {
    return Err(format!("already exists: {}", dir.display()));
  }

  let js = format!(
    r#"/**
 * src/{slot}/{name}/index.js
 *
 * Fallbacks stay by reference (dock options / library built-ins) — no 404.html.
 */
import {{ dock }} from '@adukiorg/anza/ui';

dock('{name}', {{
  parent: '{parent}',
  tag: 'dock-{name}',
  template: {{ html: './index.html', css: './index.css' }}
}}, import.meta.url);
"#,
    slot = docks_slot,
    name = name,
    parent = parent,
  );

  let html = r#"<slot></slot>
"#;
  let css = format!(
    r#":host {{
  display: block;
}}

/* dock-{name} */
"#,
    name = name
  );

  write_file(&dir.join("index.js"), &js);
  write_file(&dir.join("index.html"), html);
  write_file(&dir.join("index.css"), &css);

  let barrel = ensure_barrel(src, docks_slot, &format!("./{}/index.js", name))?;
  Ok(Generated {
    dir,
    barrel,
    kind: Kind::Dock,
    name: name.to_string(),
  })
}

fn gen_ce(
  src: &Path,
  slot: &str,
  kind_fn: &str,
  name: &str,
) -> Result<Generated, String> {
  let dir = src.join(slot).join(name);
  if dir.exists() {
    return Err(format!("already exists: {}", dir.display()));
  }

  let tag = format!("{}-{}", kind_fn, name);
  let js = format!(
    r#"/**
 * src/{slot}/{name}/index.js
 */
import {{ {kind_fn} }} from '@adukiorg/anza/ui';

{kind_fn}('{tag}', {{
  template: {{ html: './index.html', css: './index.css' }}
}}, import.meta.url);
"#,
    slot = slot,
    name = name,
    kind_fn = kind_fn,
    tag = tag,
  );

  let html = format!(
    r#"<div class="{name}">
  <slot></slot>
</div>
"#,
    name = name
  );
  let css = format!(
    r#":host {{
  display: block;
}}

.{name} {{
  /* {tag} */
}}
"#,
    name = name,
    tag = tag
  );

  write_file(&dir.join("index.js"), &js);
  write_file(&dir.join("index.html"), &html);
  write_file(&dir.join("index.css"), &css);

  let barrel = ensure_barrel(src, slot, &format!("./{}/index.js", name))?;
  let kind = if kind_fn == "view" {
    Kind::View
  } else {
    Kind::Part
  };
  Ok(Generated {
    dir,
    barrel,
    kind,
    name: name.to_string(),
  })
}

/// Ensure `src/<slot>/index.js` exists and imports `spec` (relative).
fn ensure_barrel(src: &Path, slot: &str, spec: &str) -> Result<PathBuf, String> {
  let barrel = src.join(slot).join("index.js");
  let import_line = format!("import '{}';", spec);

  if barrel.is_file() {
    let existing = fs::read_to_string(&barrel).map_err(|e| e.to_string())?;
    if existing.contains(&import_line) || existing.contains(&format!("import \"{}\"", spec)) {
      return Ok(barrel);
    }
    let mut next = existing;
    if !next.ends_with('\n') && !next.is_empty() {
      next.push('\n');
    }
    next.push_str(&import_line);
    next.push('\n');
    fs::write(&barrel, next).map_err(|e| e.to_string())?;
  } else {
    let header = format!(
      "/**\n * src/{}/index.js\n *\n * Barrel — index-per-folder convention.\n */\n",
      slot
    );
    write_file(&barrel, &format!("{}{}\n", header, import_line));
  }
  Ok(barrel)
}

fn write_file(path: &Path, content: &str) {
  if let Some(parent) = path.parent() {
    let _ = fs::create_dir_all(parent);
  }
  fs::write(path, content).unwrap_or_else(|e| {
    anza_logs::error!("Failed to write {}: {}", path.display(), e);
    std::process::exit(1);
  });
}

fn title_case(name: &str) -> String {
  name
    .split('-')
    .filter(|s| !s.is_empty())
    .map(|s| {
      let mut c = s.chars();
      match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
      }
    })
    .collect::<Vec<_>>()
    .join(" ")
}

// Resolve structure via structure::defaults (same as doctor/check).
fn resolve_paths(
  project: &Path,
  hint: &str,
) -> crate::structure::defaults::Resolved {
  crate::structure::defaults::resolve(project, hint)
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::time::{SystemTime, UNIX_EPOCH};

  fn temp(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
      "anza-gen-{}-{}-{}",
      name,
      std::process::id(),
      SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(dir.join("src")).unwrap();
    dir
  }

  fn write_file(path: &Path, content: &str) {
    if let Some(p) = path.parent() {
      fs::create_dir_all(p).unwrap();
    }
    fs::write(path, content).unwrap();
  }

  #[test]
  fn generate_page_updates_barrel() {
    let project = temp("page");
    write_file(&project.join("package.json"), r#"{ "type": "module" }"#);
    write_file(&project.join("src/pages/index.js"), "// barrel\n");
    let src = project.join("src");
    let g = run(
      &src,
      Kind::Page,
      &Options {
        name: "about".into(),
        ..Default::default()
      },
    )
    .expect("generate page");
    assert!(g.dir.join("index.js").is_file());
    assert!(g.dir.join("index.html").is_file());
    let barrel = fs::read_to_string(&g.barrel).unwrap();
    assert!(barrel.contains("import './about/index.js';"));
    let js = fs::read_to_string(g.dir.join("index.js")).unwrap();
    assert!(js.contains("page('/about'"));
    assert!(js.contains("via: ['main']"));
    let _ = fs::remove_dir_all(&project);
  }

  #[test]
  fn generate_respects_anza_json_remap() {
    let project = temp("remap");
    write_file(&project.join("package.json"), r#"{ "type": "module" }"#);
    write_file(
      &project.join("anza.json"),
      r#"{ "pages": ["routes"], "docks": "shells", "views": "ui", "rootDock": "shell" }"#,
    );
    fs::create_dir_all(project.join("src/routes")).unwrap();
    fs::create_dir_all(project.join("src/shells")).unwrap();
    fs::create_dir_all(project.join("src/ui")).unwrap();

    let src = project.join("src");
    let page = run(
      &src,
      Kind::Page,
      &Options {
        name: "home".into(),
        tree: Some("routes".into()),
        ..Default::default()
      },
    )
    .unwrap();
    assert!(page.dir.starts_with(project.join("src/routes/home")));
    let js = fs::read_to_string(page.dir.join("index.js")).unwrap();
    assert!(js.contains("via: ['shell']"));

    let dock = run(
      &src,
      Kind::Dock,
      &Options {
        name: "sidebar".into(),
        ..Default::default()
      },
    )
    .unwrap();
    assert!(dock.dir.starts_with(project.join("src/shells/sidebar")));

    let view = run(
      &src,
      Kind::View,
      &Options {
        name: "card".into(),
        ..Default::default()
      },
    )
    .unwrap();
    assert!(view.dir.starts_with(project.join("src/ui/card")));
    let _ = fs::remove_dir_all(&project);
  }

  #[test]
  fn generate_dock_no_404_file() {
    let project = temp("dock");
    write_file(&project.join("package.json"), r#"{ "type": "module" }"#);
    fs::create_dir_all(project.join("src/docks")).unwrap();
    let g = run(
      &project.join("src"),
      Kind::Dock,
      &Options {
        name: "panel".into(),
        ..Default::default()
      },
    )
    .unwrap();
    assert!(!g.dir.join("404.html").exists());
    let js = fs::read_to_string(g.dir.join("index.js")).unwrap();
    assert!(js.contains("Fallbacks stay by reference"));
    let _ = fs::remove_dir_all(&project);
  }

  #[test]
  fn rejects_unknown_page_tree() {
    let project = temp("badtree");
    write_file(&project.join("package.json"), r#"{ "type": "module" }"#);
    fs::create_dir_all(project.join("src/pages")).unwrap();
    let err = run(
      &project.join("src"),
      Kind::Page,
      &Options {
        name: "x".into(),
        tree: Some("docs".into()),
        ..Default::default()
      },
    )
    .unwrap_err();
    assert!(err.contains("pages[]"), "{}", err);
    let _ = fs::remove_dir_all(&project);
  }

  #[test]
  fn normalize_name_kebab() {
    assert_eq!(normalize_name("Hello_World").unwrap(), "hello-world");
    assert!(normalize_name("../x").is_err());
  }
}
